<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AnalysisLevel>5.0</AnalysisLevel>
        <AssemblyName>Zetatech.DeepSight.Triggers</AssemblyName>
        <AssemblyOriginatorKeyFile>$(SolutionDir)/Signature.snk</AssemblyOriginatorKeyFile>
        <AssemblyTitle>Service application for ingestion messages processing</AssemblyTitle>
        <AssemblyVersion>10.2609.0</AssemblyVersion>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <Authors>Zeta Technologies</Authors>
        <CodeAnalysisOutputToConsole>true</CodeAnalysisOutputToConsole>
        <Company>Zeta Technologies</Company>
        <Configurations>Debug;Release</Configurations>
        <ContentTargetFolders>content</ContentTargetFolders>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <Copyright>Zeta Technologies © 2026</Copyright>
        <Description>Service application for ingestion messages processing</Description>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnablePackageValidation>true</EnablePackageValidation>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <FileVersion>10.2609.0</FileVersion>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <ImplicitUsings>disable</ImplicitUsings>
        <InformationalVersion>10.2609.0</InformationalVersion>
        <IsPackable>false</IsPackable>
        <IsPublishable>true</IsPublishable>
        <IsTestProject>false</IsTestProject>
        <NeutralLanguage>en-US</NeutralLanguage>
        <Nullable>disable</Nullable>
        <OutputType>exe</OutputType>
        <Product>DeepSight Platform</Product>
        <PublishDocumentationFile>false</PublishDocumentationFile>
        <PublishDocumentationFiles>false</PublishDocumentationFiles>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/josemaria-toro/deepsight.git</RepositoryUrl>
        <RootNamespace>Zetatech.DeepSight</RootNamespace>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
        <RunCodeAnalysis>false</RunCodeAnalysis>
        <SignAssembly>true</SignAssembly>
        <TargetFramework>net10.0</TargetFramework>
        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
        <UserSecretsId>fdb97295-ad50-4a79-85ff-151c892c99d3</UserSecretsId>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
        <DefineDebug>true</DefineDebug>
        <DefineTrace>true</DefineTrace>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>false</DebugSymbols>
        <DebugType>portable</DebugType>
        <Optimize>true</Optimize>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)/Zetatech.DeepSight.Application/Zetatech.DeepSight.Application.csproj" />
        <ProjectReference Include="$(SolutionDir)/Zetatech.DeepSight.Domain/Zetatech.DeepSight.Domain.csproj" />
        <ProjectReference Include="$(SolutionDir)/Zetatech.DeepSight.Infrastructure/Zetatech.DeepSight.Infrastructure.csproj" />
    </ItemGroup>
</Project>
